version: '3.8'

services:
  viberty-bo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trivien/viberty-back-office
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
