version: '3.8'

services:
  api:
    build: .
    container_name: viberty-api
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    command: yarn dev

volumes:
  mysql-data:
