version: '3.8'

services:
  nextjs-app:
    image: trivien/viberty-mini-app
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
