name: Viberty MiniApp CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mini-app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mini-app/**'

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./mini-app
          file: ./mini-app/Dockerfile
          push: true
          tags: trivien/mini-app-react-app:latest
          no-cache: true # Force fresh build

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd viberty-network/mini-app
            docker-compose down
            docker-compose pull
            docker-compose up -d
